from authentication.views.dashboard import dashboard
from authentication.views.login import login_user
from authentication.views.word_counter import word_count_view
from authentication.views.nats_publisher import send_nats_message