from authentication.views.dashboard import dashboard
from authentication.views.login import login_user
from authentication.views.nats_publisher import send_nats_message
from authentication.views.view_infraservice import get_latest_data_json