version: "3.9"

services:
    db:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DEFAULT_DATABASE_USER}
            POSTGRES_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
            POSTGRES_DB: ${DEFAULT_DATABASE_NAME}

    napback:
        build:
            context: ../back
            dockerfile: build/Dockerfile
        env_file:
            - .env
        volumes:
            - db:/napback/db
            - static_volume:/usr/src/app/static
            - media_volume:/usr/src/app/media
        container_name: napback
        environment:
            - STAGE=dev
        ports:
            - "8000:8000"
        depends_on:
            - db
            - nats


    nats:
        image: nats:latest
        container_name: nats_server
        ports:
        - "4222:4222"  # Client port
        - "8222:8222"  # HTTP monitoring port
        - "6222:6222"  # Cluster port


    napcore:
        restart: always
        build:
            context: ../napcore
            dockerfile: build/Dockerfile
        env_file:
            - .env
        container_name: napcore
        depends_on:
            - nats
        environment:
            SSH_USERNAME: ${SSH_USERNAME}
            SSH_PASSWORD: ${SSH_PASSWORD}
            SSH_HOST: ${SSH_HOST}

    nginx:
        restart: always
        build:
            context: ../nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - napback
        volumes:
            - static_volume:/usr/src/app/static
            - media_volume:/usr/src/app/media

volumes:
    db:
    static_volume:
    media_volume:
    postgres_data:
